### PR TITLE
feat: escape html by default

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
This is technically a breaking change but it makes the usage of the tool way safer (there is a reason mustache does it that way by default).
The only thing end users will need to change is to mark their html inputs with triple {.

Another option is to make the no-escaping of mustache optional/configurable, then it can be a non breaking change.

### CODE REVIEW

**Comment by Thomascogez** [comment]
Hey! Thank for you intrest for this project, it's a really interesting point you are bringing here. I will take soon a good look a your proposed changes in order to merge this asap. Did you encounter problems with the lack of html escape ?

**Comment by AdriVanHoudt** [comment]
The main problem is that it is not documented and that you can't turn it off.
This means that by just using this module you are subjected to html injection in all email, definitely if you use some user input in the emails.
Now one can manually sanitize all data passed to the template engine but that's not very handy and, getting back to the documentation point, not obvious you need to do this.

**Comment by Thomascogez** [comment]
Yeah that a good point, it's alway a good point to have sensitive default rules about input sanitization even if it's require a bit more of overhead, I start take a look at you pr in order to merge it by the end of the week

**Comment by Thomascogez** [comment]
@AdriVanHoudt Everything seems fine, is it possible to perform dependencies install using yarn and remove the generate package-lock. If you can also check, you have a lot of diffs create by a different code formatting, is possible to keep original formatting has it make it harder to really see changes made to the codebase

**Pull request closed without merging**
